language: python

cache: pip

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

addons:
  apt:
    packages:
    - cmake
    - time

script:
  - pip install coveralls nose2 nose2-cov
  - coverage run --source=nxapi -m nose2.__main__ -v

after_success:
  - coveralls
